### ISSUE TITLE
Validation service is often down

### ISSUE THREAD

**Issue by agnelgonsal** [difi/vefa-validator#77] opened 2023-10-04 08:53 UTC
Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] Fixing my submitted issue is done by making changes to code in this repository.

Your issue here:

As online validator ( https://anskaffelser.dev/service/validator/ ) is often not available, error 504 or 502, could you give direction how to run this project on a local computer?

**Comment by klakegg** [comment] 2023-10-05 09:53
Duplicate of #75.

**Closed as completed by klakegg** 2023-10-05 09:53 UTC
